import re
from typing import List, Dict, Any, Optional, Tuple
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

REFERENCE_CORPUS: List[Dict[str, str]] = [
    {
        "id": "ref-001",
        "title": "Attention Is All You Need (Vaswani et al., 2017)",
        "author": "Vaswani et al.",
        "category": "Deep Learning / NLP",
        "text": (
            "The dominant sequence transduction models are based on complex recurrent or convolutional "
            "neural networks that include an encoder and a decoder. The best performing models also connect "
            "the encoder and decoder through an attention mechanism. We propose a new simple network architecture, "
            "the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. "
            "Experiments on two machine translation tasks show these models to be superior in quality while being more "
            "parallelizable and requiring significantly less time to train."
        )
    },
    {
        "id": "ref-002",
        "title": "BERT: Pre-training of Deep Bidirectional Transformers (Devlin et al., 2018)",
        "author": "Devlin et al.",
        "category": "NLP / Language Models",
        "text": (
            "We introduce a new language representation model called BERT, which stands for Bidirectional "
            "Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed "
            "to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left "
            "and right context in all layers. As a result, the pre-trained BERT model can be fine-tuned with just one "
            "additional output layer to create state-of-the-art models for a wide range of tasks."
        )
    },
    {
        "id": "ref-003",
        "title": "Language Models are Unsupervised Multitask Learners (Radford et al., 2019)",
        "author": "Radford et al. (OpenAI)",
        "category": "Generative Models",
        "text": (
            "Natural language processing tasks, such as question answering, machine translation, reading "
            "comprehension, and summarization, are typically approached with supervised learning on task-specific "
            "datasets. We demonstrate that language models begin to learn these tasks without any explicit supervision "
            "when trained on a new dataset of millions of webpages called WebText. When conditioned on a document plus "
            "questions, the answers generated by the language model reach state-of-the-art performance."
        )
    },
    {
        "id": "ref-004",
        "title": "Language Models are Few-Shot Learners (Brown et al., 2020)",
        "author": "Brown et al. (OpenAI)",
        "category": "Generative Models",
        "text": (
            "Recent work has demonstrated substantial gains on many NLP tasks and benchmarks by pre-training "
            "on a large corpus of text followed by fine-tuning on a specific task. Here we show that scaling up language "
            "models greatly improves task-agnostic, few-shot performance, sometimes even reaching competitiveness with "
            "prior state-of-the-art fine-tuning approaches. We train GPT-3, an autoregressive language model with "
            "175 billion parameters, and test its performance under few-shot, one-shot, and zero-shot settings."
        )
    },
    {
        "id": "ref-005",
        "title": "Computing Machinery and Intelligence (A. M. Turing, 1950)",
        "author": "Alan M. Turing",
        "category": "Philosophy / Foundations of AI",
        "text": (
            "I propose to consider the question, 'Can machines think?' This should begin with definitions "
            "of the meaning of the terms 'machine' and 'think'. The definitions might be framed so as to reflect so far "
            "as possible the normal use of the words, but this attitude is dangerous. Instead of attempting such a "
            "definition, I propose to replace the question by another, which is closely related to it and is expressed in "
            "relatively unambiguous words. The new problem can be described in terms of a game which we call the "
            "'imitation game'."
        )
    },
    {
        "id": "ref-006",
        "title": "A Mathematical Theory of Communication (C. E. Shannon, 1948)",
        "author": "Claude E. Shannon",
        "category": "Information Theory",
        "text": (
            "The fundamental problem of communication is that of reproducing at one point either exactly "
            "or approximately a message selected at another point. Frequently the messages have meaning; that is they "
            "refer to or are correlated according to some system with certain physical or conceptual entities. These "
            "semantic aspects of communication are irrelevant to the engineering problem. The significant aspect is that "
            "the actual message is one selected from a set of possible messages."
        )
    },
    {
        "id": "ref-007",
        "title": "Generative Adversarial Nets (Goodfellow et al., 2014)",
        "author": "Goodfellow et al.",
        "category": "Deep Learning / Generative Models",
        "text": (
            "We propose a new framework for estimating generative models via an adversarial process, in "
            "which we simultaneously train two models: a generative model G that captures the data distribution, "
            "and a discriminative model D that estimates the probability that a sample came from the training data "
            "rather than G. The training procedure for G is to maximize the probability of D making a mistake. "
            "This framework corresponds to a minimax two-player game."
        )
    },
    {
        "id": "ref-008",
        "title": "On the Dangers of Stochastic Parrots (Bender et al., 2021)",
        "author": "Bender et al.",
        "category": "Ethics & Safety in NLP",
        "text": (
            "Language models are trained on increasingly large web-scraped corpora. While they exhibit "
            "impressive syntactic and lexical capabilities, they lack referential grounding and replicate systemic "
            "historical biases present in their training distributions. We consider the risks associated with ever larger "
            "language models and question whether exploring ever larger architectures is the most fruitful approach to NLP."
        )
    }
]


class SemanticPlagiarismEngine:
    """
    Phase 3 Semantic Plagiarism & Paraphrase Engine.
    Employs hybrid retrieval combining dense/sparse subword TF-IDF representations
    and n-gram containment with passage-level best alignment.
    """
    def __init__(self, corpus: Optional[List[Dict[str, str]]] = None):
        self.corpus = corpus or REFERENCE_CORPUS
        self.vectorizer: Optional[TfidfVectorizer] = None
        self.corpus_matrix = None
        self._build_index()

    def _build_index(self):
        """Builds TF-IDF index across word and character n-grams."""
        corpus_texts = [doc["text"] for doc in self.corpus]
        self.vectorizer = TfidfVectorizer(
            ngram_range=(1, 3),
            analyzer="word",
            sublinear_tf=True,
            min_df=1,
            lowercase=True
        )
        self.corpus_matrix = self.vectorizer.fit_transform(corpus_texts)

    COMMON_STOPS = {
        'the', 'a', 'an', 'in', 'on', 'at', 'to', 'for', 'of', 'and', 'or', 'is', 'are',
        'was', 'were', 'it', 'with', 'as', 'by', 'that', 'this', 'we', 'i', 'be', 'from'
    }

    @classmethod
    def _calculate_directional_containment(cls, query: str, doc_text: str) -> float:
        """Computes directional stem containment: what fraction of the query's key stems appear in the doc."""
        q_stems = [w[:5] for w in re.findall(r'\b\w+\b', query.lower()) if w not in cls.COMMON_STOPS and len(w) > 2]
        d_stems = [w[:5] for w in re.findall(r'\b\w+\b', doc_text.lower()) if w not in cls.COMMON_STOPS and len(w) > 2]
        sq, sd = set(q_stems), set(d_stems)
        if not sq:
            return 0.0
        return len(sq.intersection(sd)) / len(sq)

    @staticmethod
    def _calculate_ngram_overlap(text_a: str, text_b: str, n: int = 3) -> float:
        """Computes symmetric word n-gram Jaccard / containment."""
        words_a = [w for w in re.findall(r'\b\w+\b', text_a.lower())]
        words_b = [w for w in re.findall(r'\b\w+\b', text_b.lower())]
        if len(words_a) < n or len(words_b) < n:
            # Fallback to unigram overlap for very short inputs
            set_a = set(words_a)
            set_b = set(words_b)
            if not set_a or not set_b:
                return 0.0
            return len(set_a.intersection(set_b)) / min(len(set_a), len(set_b))

        ngrams_a = set(tuple(words_a[i:i + n]) for i in range(len(words_a) - n + 1))
        ngrams_b = set(tuple(words_b[i:i + n]) for i in range(len(words_b) - n + 1))

        intersection = len(ngrams_a.intersection(ngrams_b))
        denominator = min(len(ngrams_a), len(ngrams_b))
        return intersection / denominator if denominator > 0 else 0.0

    def _find_best_passage(self, query: str, doc_text: str) -> Tuple[str, str, float]:
        """
        Locates the specific sentence/passage in the reference text that has maximum
        similarity with the query, returning (matched_passage, user_passage, score).
        """
        sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', doc_text) if s.strip()]
        if not sentences:
            return doc_text[:280] + "...", query[:280] + "...", 0.0

        best_sent = sentences[0]
        best_score = 0.0

        for sent in sentences:
            ov = self._calculate_ngram_overlap(query, sent, n=2)
            cont = self._calculate_directional_containment(query, sent)
            score = max(ov, cont)
            if score > best_score:
                best_score = score
                best_sent = sent

        matched_snippet = best_sent if len(best_sent) <= 280 else best_sent[:280] + "..."
        user_snippet = query if len(query) <= 280 else query[:280] + "..."
        return matched_snippet, user_snippet, best_score

    def scan_text(
        self,
        text: str,
        threshold: float = 0.40,
        top_k: int = 5
    ) -> Dict[str, Any]:
        """
        Scans input text against indexed corpus with hybrid semantic + n-gram matching.
        """
        if not text or not text.strip():
            return {
                "overall_similarity": 0.0,
                "paraphrase_likelihood": "Low",
                "classification": "AUTHENTIC",
                "confidence": "HIGH",
                "signals": ["Empty or whitespace input"],
                "matches": []
            }

        text_cleaned = text.strip()
        query_vec = self.vectorizer.transform([text_cleaned])
        cosine_sims = cosine_similarity(query_vec, self.corpus_matrix)[0]

        matches = []
        max_score = 0.0

        for idx, doc in enumerate(self.corpus):
            dense_sim = float(cosine_sims[idx])
            ngram_overlap_2 = self._calculate_ngram_overlap(text_cleaned, doc["text"], n=2)
            ngram_overlap_3 = self._calculate_ngram_overlap(text_cleaned, doc["text"], n=3)
            containment = self._calculate_directional_containment(text_cleaned, doc["text"])

            matched_snippet, user_snippet, passage_overlap = self._find_best_passage(text_cleaned, doc["text"])
            effective_overlap = max(ngram_overlap_2, passage_overlap)

            # Directional hybrid blended score
            blended_score = max(
                dense_sim,
                effective_overlap * 0.95,
                (dense_sim * 0.35) + (effective_overlap * 0.65),
                containment * 0.85,
                (dense_sim * 0.30) + (containment * 0.70)
            )
            blended_score = float(np.clip(blended_score, 0.0, 0.99))

            if blended_score >= threshold:
                if blended_score > max_score:
                    max_score = blended_score

                # Determine match type with fine-grained taxonomy
                if ngram_overlap_3 >= 0.60 or passage_overlap >= 0.70:
                    match_type = "exact"
                elif effective_overlap >= 0.35:
                    match_type = "near_duplicate"
                elif containment >= 0.30 or dense_sim >= 0.25:
                    match_type = "paraphrase"
                else:
                    match_type = "semantic"

                matches.append({
                    "source_id": doc["id"],
                    "source_title": doc["title"],
                    "similarity_score": round(blended_score, 2),
                    "match_type": match_type,
                    "matched_text": matched_snippet,
                    "user_passage": user_snippet
                })

        # Sort matches descending by score
        matches.sort(key=lambda m: m["similarity_score"], reverse=True)
        matches = matches[:top_k]

        # Aggregate likelihood & classification
        if max_score >= 0.75:
            paraphrase_likelihood = "High"
            classification = "POTENTIALLY_MANIPULATED"
            confidence = "HIGH"
        elif max_score >= 0.48:
            paraphrase_likelihood = "Medium"
            classification = "POTENTIALLY_MANIPULATED"
            confidence = "MEDIUM"
        else:
            paraphrase_likelihood = "Low"
            classification = "AUTHENTIC"
            confidence = "HIGH"

        signals = []
        if max_score >= 0.75:
            signals.append("Substantial verbatim or structural concordance with indexed literature")
        elif max_score >= 0.48:
            signals.append("Elevated semantic similarity and paraphrased sentence alignment detected")
        else:
            signals.append("Original authorship: no significant cross-corpus concordance detected")

        return {
            "overall_similarity": round(max_score * 100, 1),
            "probability": round(max_score, 2),
            "paraphrase_likelihood": paraphrase_likelihood,
            "classification": classification,
            "confidence": confidence,
            "signals": signals,
            "matches": matches
        }

    def get_indexed_corpus_summary(self) -> List[Dict[str, str]]:
        """Returns indexed corpus catalog."""
        return [
            {
                "id": doc["id"],
                "title": doc["title"],
                "author": doc.get("author", "Unknown"),
                "category": doc.get("category", "General"),
                "word_count": len(doc["text"].split())
            }
            for doc in self.corpus
        ]


# Singleton instance initialized with expanded benchmark corpus
semantic_engine = SemanticPlagiarismEngine()
