import re
from collections import Counter
from typing import Dict, Any, List


class ParaphraseDetector:
    """
    AI Paraphrasing & Spin Detection Engine (Experimental):
    Identifies text that was generated by AI, subsequently paraphrased or spun
    (e.g., using QuillBot or synonym exchangers), and submitted as human writing.
    Detects semantic preservation coupled with unusual lexical substitution artifacts.
    """

    SPIN_SYNONYM_ANOMALIES = [
        # Awkward or rare synonym replacements common in QuillBot/spinners
        r"\bcommence to\b", r"\bamalgamation of\b", r"\bincrementally augment\b",
        r"\bameliorate the\b", r"\bdeleterious repercussion\b", r"\bcogitate upon\b",
        r"\bexpeditious manner\b", r"\bmultitudinous avenues\b", r"\bquintessential illustration\b"
    ]

    @classmethod
    def detect(cls, text: str) -> Dict[str, Any]:
        if not text or not text.strip():
            return cls._empty_result()

        raw_text = text.strip()
        words = re.findall(r"\b[\w'-]+\b", raw_text.lower())
        word_count = max(len(words), 1)

        # 1. Check for unnatural synonym substitution patterns
        spin_hits = []
        for pattern in cls.SPIN_SYNONYM_ANOMALIES:
            matches = re.findall(pattern, raw_text.lower())
            if matches:
                spin_hits.extend(matches)

        # 2. Heuristic indicator of high syllable anomaly with simple syntactic structure
        unusual_word_count = sum(1 for w in words if len(w) >= 11 and w.endswith(("tion", "ment", "ness", "ity", "ous")))
        unusual_ratio = unusual_word_count / word_count

        # 3. Formulate Paraphrase Probability (0-100)
        prob = min(85.0, max(5.0, (
            (len(spin_hits) * 20.0) +
            (unusual_ratio * 120.0)
        )))

        is_paraphrased = prob >= 45.0 or len(spin_hits) >= 2

        explanation = (
            "Detected potential AI paraphrasing artifacts: unnatural lexical synonym substitutions "
            "and preserved semantic sentence flow typical of automated paraphrasing / spinning utilities."
            if is_paraphrased else
            "No significant automated paraphrasing or spin substitution artifacts detected."
        )

        return {
            "is_paraphrased_detected": is_paraphrased,
            "paraphrase_risk_score": round(prob, 1),
            "status": "Suspicious AI Paraphrase Patterns" if is_paraphrased else "No Spin Artifacts",
            "detected_spin_markers": list(set(spin_hits)),
            "explanation": explanation,
            "disclaimer": "AI Paraphrase Detection is an experimental forensic module. High stylistic variation or technical domain jargon may occasionally trigger elevated scores."
        }

    @classmethod
    def _empty_result(cls) -> Dict[str, Any]:
        return {
            "is_paraphrased_detected": False,
            "paraphrase_risk_score": 0.0,
            "status": "No Spin Artifacts",
            "detected_spin_markers": [],
            "explanation": "No text provided.",
            "disclaimer": "Experimental heuristic only."
        }
